twig:
    default_path: '%kernel.project_dir%/templates'
    # form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        devmode: '%env(APP_ENV)%'
when@test:
    twig:
        strict_variables: true
