USE BOMERLEDB;
ALTER TABLE knifes MODIFY COLUMN stock int NULL;
ALTER TABLE knifes MODIFY COLUMN cuttingedge_lenght int NULL;
ALTER TABLE knifes MODIFY COLUMN lenght int NULL;
ALTER TABLE knifes MODIFY COLUMN weight int NULL;
ALTER TABLE knifes MODIFY COLUMN close_lenght int NULL;
